# Generated by Django 3.1.3 on 2020-11-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('passowrd', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField(max_length=14)),
                ('avatar', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=100)),
                ('Provider', models.CharField(choices=[('mail', 'email'), ('facebook', 'facebook')], max_length=50)),
                ('country', models.CharField(max_length=50, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('facebook_profile', models.CharField(max_length=100, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_acive', models.BooleanField(default=False)),
            ],
        ),
    ]
