# Generated by Django 3.1.3 on 2020-11-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
