# Generated by Django 3.1.3 on 2020-11-27 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0002_auto_20201118_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_acive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='is_admin',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='users',
            name='avatar',
        ),
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile_number',
            field=models.IntegerField(blank=True, validators=[django.core.validators.RegexValidator(message='Phone number must match egyptian format', regex='^01[1|0|2|5][0-9]{8}$')]),
        ),
    ]
