# Generated by Django 3.1.3 on 2020-11-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0003_auto_20201127_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
