# Generated by Django 3.1.3 on 2020-11-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglogin', '0004_auto_20201127_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile_number',
            field=models.IntegerField(blank=True),
        ),
    ]
