# Generated by Django 3.1.3 on 2020-11-19 22:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2020, 11, 19, 22, 43, 12, 540316, tzinfo=utc)),
        ),
    ]
