# Generated by Django 3.1.3 on 2020-11-20 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201118_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2020, 11, 20, 12, 33, 22, 882312, tzinfo=utc)),
        ),
    ]
