# Generated by Django 3.1.3 on 2020-11-27 21:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201120_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2020, 11, 27, 21, 57, 15, 341635, tzinfo=utc)),
        ),
    ]
