# Generated by Django 3.1.3 on 2020-11-20 19:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201120_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2020, 11, 20, 19, 9, 31, 61785, tzinfo=utc)),
        ),
    ]
