# Generated by Django 3.1.3 on 2020-11-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201123_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('title',)},
        ),
    ]
