# Generated by Django 3.1.3 on 2020-11-27 21:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201127_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2020, 11, 27, 21, 58, 44, 323117, tzinfo=utc)),
        ),
    ]
