# Generated by Django 3.1.3 on 2020-11-20 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201120_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2020, 11, 20, 19, 34, 15, 430072, tzinfo=utc)),
        ),
    ]
