# Generated by Django 3.1.3 on 2020-11-23 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201123_1350'),
        ('projects', '0005_auto_20201120_2134'),
    ]

    operations = [
    ]
