# Generated by Django 3.1.3 on 2020-11-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201120_0045'),
        ('projects', '0006_merge_20201123_1844'),
    ]

    operations = [
    ]
